port = ":8080"
database_url = "host=auth-pg dbname=notebook sslmode=disable user=postgres password=password" 
nats_url = "nats://nats:4222"
[redis]
    addr = "redis:6379"
    password = ""
    db = 0